version: 2.1
orbs:
  slack: circleci/slack@3.4.0
  vsce: uraway/vsce@0.0.4
jobs:
  test:
    executor: vsce/node-browsers
    steps:
      - slack/notify:
          message: "A vscode-tilt release has started!"
      - checkout
workflows:
  test-publish:
    jobs:
      - test:
          context:
            - Tilt Slack Context
      - vsce/publish:
          context:
            - Tilt VSCE Context
          filters:
            branches:
              only: never-release-on-a-branch
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+/
          post-install-steps:
            - save_cache:
                key: 'v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}'
                paths:
                  - node_modules
          pre-install-steps:
            - restore_cache:
                keys:
                  - >-
                    v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json"
                    }}
                  - 'v1-node-cache-{{ .Branch }}'
                  - v1-node-cache-
          publish-token-variable: VSCODE_MARKETPLACE_TOKEN
          push-git-tag: false
          requires:
            - test

